### ISSUE TITLE
Dev Ops - Dockerize the database

### ISSUE THREAD

**Issue by priime0** [Northeastern-Electric-Racing/FinishLine#10]
# Description
Dockerizing the database would enable the easier onboarding of developers as it removes the headache of setting up the dev environment. It will allow newer developers to start contributing and experimenting with the project faster.

# Proposed Solution
Google how to dockerize a postgres db I guess? Basically if new devs can get it set up by just downloading docker then running one or two docker commands then that will be a huge win.

**Comment by anthonybernardi** [comment]
No need for a PR really since the onboarding docs are now separate from the repo with Arnav's updates. Here's the steps though:

1. install docker
2. docker run --name finishline -e POSTGRES_PASSWORD=docker -p 5432:5432 -d postgres
3. docker exec -ti finishline psql -U postgres -c “CREATE DATABASE nerpm;”
4. Then the url in the .env is always DATABASE_URL="postgresql://postgres:docker@localhost:5432/nerpm?schema=public"

It works the exact same on windows and mac!

notes: if you already have your old postgres running you have to stop it first.

**Comment by anthonybernardi** [comment]
above solution is good, will incorporate it into the onboarding for the fall
