### ISSUE TITLE
[Spike] - Slack Message in Thread when a CR is Approved/ Implemented

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#1518]
### Spike Type

Technical

### Goal

Figure out how to get the Slackbot to reply in a thread it has created

### Reason for Spike

Ideally the slackbot would reply in the original thread that it creates when a CR is created when the CR is approved (we could also move any reviewer requests into this thread as well), but we need to figure out how we would do this

**Comment by sharonyang16** [comment]
## Here is a way we could do it:

To find the the original message, we can use the ``search.messages`` method (https://api.slack.com/methods/search.messages). The two required arguments to use this method is the Slack token and a search query. In the search query, we can include the CR number that is being approved/implemented. We can also include in the query that we’re only looking for messages from a specific user (i.e. our slackbot).

To specify who the message was from, we would include “from:<@UserID>” in our query. So in this case, we would want to include “from:@finishline_by_ner” in our query.

So for example, if we wanted to find the original message the slackbot sent when CR#9999 was created, our query could be ``query: “from:@finishline_by_ner 9999”``. 

From a successful result from calling ``search.messages`` (see the “Common successful response” result from https://api.slack.com/methods/search.messages#examples for a visual example), we would want the grab the ``messages.matches`` (which is an array) and for each match, we would grab the ``channel.id`` and the ``ts`` (timestamp) to use in our ``chat.postMessage`` call. The inclusion of the ``thread_ts`` argument is what makes the message sent from calling ``chat.postMessage`` a reply instead of a new unthreaded message (stated here: https://api.slack.com/methods/chat.postMessage#arg_thread_ts).
