### ISSUE TITLE
[Frontend] - Gantt Chart cut off when all projects are expanded

### ISSUE THREAD

**Issue by Ari-S-123** [Northeastern-Electric-Racing/FinishLine#779]
### Browser(s)

Chrome

### Platform(s)

Desktop

### Observed Behavior

When there are a lot of projects visible and they are all expanded, the Gantt Chart gets cut off at the bottom.

### Expected Behavior

The Gantt Chart should not be getting cut off in any place.

### Steps to Reproduce

1. Go to the Gantt Page
2. Select All Statuses
3. Click Expand
4. Scroll to the bottom and observe

### Screenshots (as needed)

![image](https://user-images.githubusercontent.com/80832201/215870255-aea9f3e8-47ff-4c34-81b0-819d94780976.png)

**Comment by jonathan-chen10** [comment]
This is not due to the number of projects but rather because some of the longer project/WP names are being wrapped, and the chart is not adjusting.

![Screen Shot 2023-02-05 at 11 25 41 AM](https://user-images.githubusercontent.com/59806366/216831520-91dc260e-5c4a-4ebc-be18-9c3e891a43ec.png)

Possible solutions:
- Cut off the project name, maybe put '...' at the end
- Change the spacing in the chart to match the labels (probably harder)
